### ISSUE TITLE
Import 

### ISSUE THREAD

**Issue by rafaelcanovas** [sakamotorafael/flask_exercise#1]
https://github.com/sakamotorafael/flask_exercise/blob/114ed7881210ea4b15d2bfa517a839c32718451f/controller/api/depts_controller.py#L1

Fala Rafa, tudo bem?

Qual seria a função deste import?

Abs.

**Comment by sakamotorafael** [comment]
Oi, Rafa! Esse import está aí por engano. Eu não tô reconhecendo ele... rs... Provavelmente foi importado automaticamente pela IDE enquanto eu escrevia o código eu não notei...

**Comment by rafaelcanovas** [comment]
Hehehe ok, obrigado Rafa!
