### ISSUE TITLE
Type-hint de argumento

### ISSUE THREAD

**Issue by rafaelcanovas** [sakamotorafael/flask_exercise#2]
https://github.com/sakamotorafael/flask_exercise/blob/114ed7881210ea4b15d2bfa517a839c32718451f/service/response_payloads_service.py#L24-L27

Fala Rafa, tudo bem?

Neste caso temos o argumento `dept_id` tipado como `int`, no entanto, mais abaixo há uma comparação `dept_id == None`, portanto o type-hint está incorreto.

Como você o corrigiria?

Abs.

**Comment by sakamotorafael** [comment]
Rafa, a comparação não é com o dept_id, mas com o dept, que deveria ser um departamento retornado pela query. Se a query retornar None, eu mando a api retornar uma Response com status 404 e a mensagem "O departamento X não foi encontrado.", sendo X o id passado no parâmetro.

**Comment by rafaelcanovas** [comment]
É verdade Rafa, obrigado!
